function y = NEWga_f_pso(x)
% load ./data/data_factor
%      W=c(:,t)+hw*eps_I(:,t)+hu*phi_G(:,t);
%      factor(1:dc,:)=Q;% ai
%      factor(dc+1:2*dc,:)=(V.*alpha.*(W.*PUE+hw*eps_D)-Q); % bi
%      factor(2*dc+1:3*dc,:)=(X+V.*W); % D
%      factor(3*dc+1:4*dc,:)=V.*(hu*phi_r-W); % r


load ./data/data_factor_ga_pso_factor factor At cons_inAeq
gx = cons_inAeq * [x(1), x(2),x(3),x(4),x(5),x(6),x(7),x(8),x(9),x(10),x(11),x(12),x(13),x(14),x(15),x(16)]';
% size(gx)
y = factor(1)*x(1)+ ...
    factor(2)*x(2) + ...
    factor(3)*x(3) + ...
    factor(4)*x(4) + ...
    factor(5)*x(5) + ...
    factor(6)*x(6) + ...
    factor(7)*x(7) + ...
    factor(8)*x(8) + ...
    factor(9)*x(9) + ...
    factor(10)*x(10) + ...
    factor(11)*x(11) + ...
    factor(12)*x(12) + ...
    factor(13)*x(13) + ...
    factor(14)*x(14) + ...
    factor(15)*x(15) + ...
    factor(16)*x(16) +...
    1e5*(abs(At-x(1)-x(2)-x(3)-x(4))^2 +...
    max(0, gx(1))^2 +...
    max(0, gx(2))^2 +...
    max(0, gx(3))^2 +...
    max(0, gx(4))^2 );
end